spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to Bank accounts related QA APIs"
  contactDetails:
    name: "John Doe - QA Lead"
    email: "john@test.com"
  onCallSupport:
    - 1234567890